import type { Subscription } from "../types";

const now = Date.now();

export const mockSubscriptions: Subscription[] = [
  {
    id: "1",
    name: "Netflix",
    category: "Entertainment",
    cost: 649,
    billingCycle: "monthly",
    purchaseDate: new Date(now - 10 * 86400000).toISOString(),
    lastUsed: new Date(now - 2 * 86400000).toISOString(),
    status: "active",
    logo: "🎬",
    createdAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "2",
    name: "Spotify",
    category: "Music",
    cost: 119,
    billingCycle: "monthly",
    purchaseDate: new Date(now - 15 * 86400000).toISOString(),
    lastUsed: new Date(now - 1 * 86400000).toISOString(),
    status: "active",
    logo: "🎵",
    createdAt: new Date("2024-01-15").toISOString(),
  },
  {
    id: "3",
    name: "Amazon Prime",
    category: "Entertainment",
    cost: 1499,
    billingCycle: "yearly",
    purchaseDate: new Date(now - 200 * 86400000).toISOString(),
    lastUsed: new Date(now - 45 * 86400000).toISOString(),
    status: "unused",
    logo: "📦",
    createdAt: new Date("2024-02-01").toISOString(),
  },
  {
    id: "4",
    name: "SonyLIV",
    category: "Entertainment",
    cost: 299,
    billingCycle: "monthly",
    purchaseDate: new Date(now - 40 * 86400000).toISOString(),
    lastUsed: new Date(now - 60 * 86400000).toISOString(),
    status: "unused",
    logo: "📺",
    createdAt: new Date("2024-02-10").toISOString(),
  },
  {
    id: "5",
    name: "YouTube Premium",
    category: "Entertainment",
    cost: 189,
    billingCycle: "monthly",
    purchaseDate: new Date(now - 12 * 86400000).toISOString(),
    lastUsed: new Date(now - 3 * 86400000).toISOString(),
    status: "active",
    logo: "▶️",
    createdAt: new Date("2024-03-01").toISOString(),
  },
  {
    id: "6",
    name: "iCloud Storage",
    category: "Cloud",
    cost: 75,
    billingCycle: "monthly",
    purchaseDate: new Date(now - 5 * 86400000).toISOString(),
    lastUsed: new Date(now).toISOString(),
    status: "active",
    logo: "☁️",
    createdAt: new Date("2024-01-20").toISOString(),
  },
  {
    id: "7",
    name: "Hotstar",
    category: "Entertainment",
    cost: 299,
    billingCycle: "monthly",
    purchaseDate: new Date(now - 60 * 86400000).toISOString(),
    lastUsed: new Date(now - 90 * 86400000).toISOString(),
    status: "unused",
    logo: "⭐",
    createdAt: new Date("2024-02-15").toISOString(),
  },
  {
    id: "8",
    name: "Notion",
    category: "Productivity",
    cost: 400,
    billingCycle: "monthly",
    purchaseDate: new Date(now - 8 * 86400000).toISOString(),
    lastUsed: new Date(now - 5 * 86400000).toISOString(),
    status: "active",
    logo: "📝",
    createdAt: new Date("2024-03-10").toISOString(),
  },
];

export const CATEGORY_COLORS: Record<string, string> = {
  Entertainment: "#4f8ef7",
  Productivity: "#00e5b0",
  Music: "#a78bfa",
  Cloud: "#f5a623",
  Gaming: "#ff4d6a",
  Fitness: "#34d399",
  News: "#60a5fa",
  Other: "#6b7f9e",
};
