import type { Subscription } from "../types";

export const mockSubscriptions: Subscription[] = [
  {
    id: "1",
    name: "Netflix",
    category: "Entertainment",
    cost: 649,
    billingCycle: "monthly",
    lastUsed: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    renewalDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    logo: "🎬",
    createdAt: new Date("2024-01-01").toISOString(),
  },
  {
    id: "2",
    name: "Spotify",
    category: "Music",
    cost: 119,
    billingCycle: "monthly",
    lastUsed: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    renewalDate: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    logo: "🎵",
    createdAt: new Date("2024-01-15").toISOString(),
  },
  {
    id: "3",
    name: "Amazon Prime",
    category: "Entertainment",
    cost: 299,
    billingCycle: "monthly",
    lastUsed: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    renewalDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "unused",
    logo: "📦",
    createdAt: new Date("2024-02-01").toISOString(),
  },
  {
    id: "4",
    name: "SonyLIV",
    category: "Entertainment",
    cost: 299,
    billingCycle: "monthly",
    lastUsed: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    renewalDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: "unused",
    logo: "📺",
    createdAt: new Date("2024-02-10").toISOString(),
  },
  {
    id: "5",
    name: "YouTube Premium",
    category: "Entertainment",
    cost: 189,
    billingCycle: "monthly",
    lastUsed: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    renewalDate: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    logo: "▶️",
    createdAt: new Date("2024-03-01").toISOString(),
  },
  {
    id: "6",
    name: "iCloud Storage",
    category: "Cloud",
    cost: 75,
    billingCycle: "monthly",
    lastUsed: new Date(Date.now() - 0).toISOString(),
    renewalDate: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    logo: "☁️",
    createdAt: new Date("2024-01-20").toISOString(),
  },
  {
    id: "7",
    name: "Hotstar",
    category: "Entertainment",
    cost: 299,
    billingCycle: "monthly",
    lastUsed: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    renewalDate: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    status: "unused",
    logo: "⭐",
    createdAt: new Date("2024-02-15").toISOString(),
  },
  {
    id: "8",
    name: "Notion",
    category: "Productivity",
    cost: 400,
    billingCycle: "monthly",
    lastUsed: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    renewalDate: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000).toISOString(),
    status: "active",
    logo: "📝",
    createdAt: new Date("2024-03-10").toISOString(),
  },
];

export const CATEGORY_COLORS: Record<string, string> = {
  Entertainment: "#4f8ef7",
  Productivity: "#00e5b0",
  Music: "#a78bfa",
  Cloud: "#f5a623",
  Gaming: "#ff4d6a",
  Fitness: "#34d399",
  News: "#60a5fa",
  Other: "#6b7f9e",
};
